# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build ferris_rev02'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["ferris_rev02_left","ferris_rev02_right"]'
      clipboard: '["mac"]'
      custom_config: '["#define MIRYOKU_EXTRA_APTV5"]'
